# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3123e9d600d220751508672699b95af91964ed626699e013f1171be04001864be4fd369a3dcaa0ceb63c8197cb9a5d9a7f4cfa5b598568731572819f225cc978

test:
  secret_key_base: 4fbed39e4c145e625012c9ff5cc69c40fd2fb5caba03466348597dbdac046755f561632be04c3a1cc362fa7660912c9cea698e638bf812209464b87e9dd891a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
